version: '3'
networks:
  front-end:

services:
  front:
    container_name: front-end
    build:
      context: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    networks:
      - front-end
    ports:
      - 8080:3000
